[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "precommit-hooks"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
adr-scanner = "hooks.adr_scanner:main"